# Occupation

### Introduction:

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

### Step 3. Assign it to a variable called users.

In [2]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user"
users = pd.read_csv(url, sep="|")
users

     user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]

### Step 4. Discover what is the mean age per occupation

In [4]:
round(users.groupby("occupation").age.mean(),0)

occupation
administrator    39.0
artist           31.0
doctor           44.0
educator         42.0
engineer         36.0
entertainment    29.0
executive        39.0
healthcare       42.0
homemaker        33.0
lawyer           37.0
librarian        40.0
marketing        38.0
none             27.0
other            35.0
programmer       33.0
retired          63.0
salesman         36.0
scientist        36.0
student          22.0
technician       33.0
writer           36.0
Name: age, dtype: float64

### Step 5. Discover the Male ratio per occupation and sort it from the most to the least

In [24]:
df_total = users.groupby("occupation").gender.size()
male = users[users.gender == "M"]
df_male = male.groupby("occupation").gender.size()
ratio = df_male / df_total
ratio.sort_values(ascending=False)

occupation
doctor           1.000000
engineer         0.970149
technician       0.962963
retired          0.928571
programmer       0.909091
executive        0.906250
scientist        0.903226
entertainment    0.888889
lawyer           0.833333
salesman         0.750000
educator         0.726316
student          0.693878
other            0.657143
marketing        0.615385
writer           0.577778
none             0.555556
administrator    0.544304
artist           0.535714
librarian        0.431373
healthcare       0.312500
homemaker        0.142857
Name: gender, dtype: float64

### Step 6. For each occupation, calculate the minimum and maximum ages

In [25]:
users.groupby("occupation")["age"].agg(["min", "max"])

               min  max
occupation
administrator   21   70
artist          19   48
doctor          28   64
educator        23   63
engineer        22   70
entertainment   15   50
executive       22   69
healthcare      22   62
homemaker       20   50
lawyer          21   53
librarian       23   69
marketing       24   55
none            11   55
other           13   64
programmer      20   63
retired         51   73
salesman        18   66
scientist       23   55
student          7   42
technician      21   55
writer          18   60

### Step 7. For each combination of occupation and gender, calculate the mean age

In [27]:
round(users.groupby(["occupation","gender"])["age"].mean(),0)

occupation     gender
administrator  F         41.0
               M         37.0
artist         F         30.0
               M         32.0
doctor         M         44.0
educator       F         39.0
               M         43.0
engineer       F         30.0
               M         37.0
entertainment  F         31.0
               M         29.0
executive      F         44.0
               M         38.0
healthcare     F         40.0
               M         45.0
homemaker      F         34.0
               M         23.0
lawyer         F         40.0
               M         36.0
librarian      F         40.0
               M         40.0
marketing      F         37.0
               M         38.0
none           F         36.0
               M         19.0
other          F         35.0
               M         34.0
programmer     F         32.0
               M         33.0
retired        F         70.0
               M         63.0
salesman       F         27.0
               M         39.0
scientist      F         28.0
               M         36.0
student        F         21.0
               M         23.0
technician     F         38.0
               M         33.0
writer         F         38.0
               M         35.0
Name: age, dtype: float64

### Step 8.  For each occupation present the percentage of women and men

In [34]:
print("male percentage:")
display(df_male / df_total)

print("women:")
display(1-df_male / df_total)

male percentage:

occupation
administrator    0.544304
artist           0.535714
doctor           1.000000
educator         0.726316
engineer         0.970149
entertainment    0.888889
executive        0.906250
healthcare       0.312500
homemaker        0.142857
lawyer           0.833333
librarian        0.431373
marketing        0.615385
none             0.555556
other            0.657143
programmer       0.909091
retired          0.928571
salesman         0.750000
scientist        0.903226
student          0.693878
technician       0.962963
writer           0.577778
Name: gender, dtype: float64

women:

occupation
administrator    0.455696
artist           0.464286
doctor           0.000000
educator         0.273684
engineer         0.029851
entertainment    0.111111
executive        0.093750
healthcare       0.687500
homemaker        0.857143
lawyer           0.166667
librarian        0.568627
marketing        0.384615
none             0.444444
other            0.342857
programmer       0.090909
retired          0.071429
salesman         0.250000
scientist        0.096774
student          0.306122
technician       0.037037
writer           0.422222
Name: gender, dtype: float64

In [36]:
users.groupby(["occupation","gender"]).agg({"gender":"count"})

                      gender
occupation    gender
administrator F           36
              M           43
artist        F           13
              M           15
doctor        M            7
educator      F           26
              M           69
engineer      F            2
              M           65
entertainment F            2
              M           16
executive     F            3
              M           29
healthcare    F           11
              M            5
homemaker     F            6
              M            1
lawyer        F            2
              M           10
librarian     F           29
              M           22
marketing     F           10
              M           16
none          F            4
              M            5
other         F           36
              M           69
programmer    F            6
              M           60
retired       F            1
              M           13
salesman      F            3
              M            9
scientist     F            3
              M           28
student       F           60
              M          136
technician    F            1
              M           26
writer        F           19
              M           26