# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [27]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [28]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
chipo = pd.read_csv(url, sep = "\t")
chipo.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

### Step 4. How many products cost more than $10.00?

In [29]:
chipo.info()

<class 'pandas.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   str
 3   choice_description  3376 non-null   str
 4   item_price          4622 non-null   str
dtypes: int64(2), str(3)
memory usage: 490.3 KB

In [30]:
# mask = chipo["item_price"].str.replace("$","")
# mask
# chipo["item_price"] = pd.to_numeric(mask, errors="coerce")
# chipo["item_price"]

chipo["item_price"] = chipo["item_price"].apply(lambda x: float(x[1:]))
chipo["item_price"]

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
        ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: float64

In [33]:
subset = chipo[chipo["item_price"] > 10]
subset["item_name"].nunique()

31

### Step 5. What is the price of each item? 
###### print a data frame with only three columns item_name choice_description and product_price

In [37]:
df = subset[["item_name","choice_description", "item_price"]]
df

,item_name,choice_description,item_price
4,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
5,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98
7,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75
13,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
23,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",10.98
...,...,...,...
4610,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4611,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",11.25
4617,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25

### Step 6. Sort by the name of the item

In [39]:
df.sort_values(by = "item_name",inplace=True)
df

,item_name,choice_description,item_price
3389,6 Pack Soft Drink,[Diet Coke],12.98
39,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.75
58,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.75
136,Barbacoa Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75
471,Barbacoa Bowl,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",11.48
...,...,...,...
4201,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Black...",11.25
4261,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
738,Veggie Soft Tacos,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
1699,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
3889,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",16.98

### Step 7. What was the quantity of the most expensive item ordered?

In [43]:
expensive = chipo["item_price"].max()
answer = chipo[chipo["item_price"] == expensive]
answer.quantity

3598    15
Name: quantity, dtype: int64

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [48]:
print(chipo[chipo["item_name"]=="Veggie Salad Bowl"]["quantity"].sum())

18

### Step 9. How many times did someone order more than one Canned Soda?

In [60]:
chipo[(chipo["item_name"] == "Canned Soda") & (chipo["quantity"] > 1)].shape[0]

20